name: Push-to-EC2

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: tsc compile
        run: |
          tsc

      - name: move everything to EC2
        uses: easingthemes/ssh-deploy@main
        with:
          ARGS: "--delete -rlgoDzvc -i"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: run commands on the EC2
        uses: appleboy/ssh-action@master
        env:
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
          TOKEN: ${{secrets.TOKEN}}
          FB_PROJECT_ID: ${{secrets.FB_PROJECT_ID}}
          FB_PRIVATE_KEY: ${{secrets.FB_PRIVATE_KEY}}
          FB_CLIENT_EMAIL: ${{secrets.FB_CLIENT_EMAIL}}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: TARGET_DIR,TOKEN,FB_PROJECT_ID,FB_PRIVATE_KEY,FB_CLIENT_EMAIL,OPENAI_API_KEY
          script: |
            cd $TARGET_DIR
            sudo npm install -g forever
            forever stopall
            forever start ./dist/index.js

